language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t regokan/travis-react -f Dockerfile.dev .

script:
  - docker run -e CI=true regokan/travis-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "travis-react"
  env: "TravisReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-259246440996"
  bucket_path: "travis-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
