language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t regokan/travis-react -f Dockerfile.dev .

script:
  - docker run -r CI=true regokan/travis-react npm run test
